version: "3.3"
services:
  mysql:
    image: arm64v8/mysql:8-oracle
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=2048
      --lower_case_table_names=1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Power4005
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    ports:
      - '3306:3306'
    volumes:
      - "./mysql8/data/db:/var/lib/mysql"
#      - "./mysql8/conf/my.cnf:/etc/mysql/my.cnf"
  nacos:
    image: nacos/nacos-server:v2.1.0-slim
    container_name: nacos-standalone-mysql
    env_file:
      - ./nacos/env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8001:8848"
      - "9555:9555"
      - "9848:9848"
    restart: always
    depends_on:
      - mysql