version: "3.3"
services:
  mysql:
    image: arm64v8/mysql:8-oracle
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=2048
      --lower_case_table_names=1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Power4005
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    ports:
      - '3306:3306'
    volumes:
      - "./mysql8/data/db:/var/lib/mysql"