version: '3.7'

networks:
  kafka-network:
    name: kafka_network
    ipam:
      driver: default
      config:
        - subnet: 192.169.0.0/24
          ip_range: 192.169.0.0/24
services:
  zookeeper:
    image: zookeeper
    volumes:
      - ./data:/data
    ports:
      - 2182:2181
    networks:
      kafka-network:
        ipv4_address: 192.169.0.2
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.169.0.3:9092
      KAFKA_CREATE_TOPICS: "kafeidou:2:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./kafka-logs:/kafka
    depends_on:
      - zookeeper
    networks:
      kafka-network:
        ipv4_address: 192.169.0.3
  kafdrop:
    image: obsidiandynamics/kafdrop:3.30.0
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka

    networks:
      - kafka-network